
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'gradle clean test -Dtags=confirmOrder'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false